version: "3.8"

services:
  frontend:
    image: morfis/frontend
    build: ./frontend/
    container_name: frontend_app
    environment:
      - BROWSER_BASE_URL=http://localhost/api/v1/
      - BASE_URL=backend_app
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
#    ports:
#      - "3000:3000"
    expose:
      - "3000"

  database:
    image: postgres:14-alpine
    container_name: database_app
    env_file:
      - ./env/.env.dev-docker
    volumes:
      - ./database/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
      - pg_database:/var/lib/postgresql/data

  backend:
    image: morfis/backend
    container_name: backend_app
    build: ./backend/
    env_file:
      - ./env/.env.dev-docker
    expose:
      - "8000"
    command: sh -c "
      ./manage.py collectstatic --no-input
      && ./manage.py migrate
      && gunicorn --bind :8000 --workers 3 app.wsgi
      && ./manage.py loaddata ./fixtures/users.json ./fixtures/icd_code.json"
    volumes:
      - ./static/:/app/static

  web:
    container_name: web_app
    image: nginx:1.19.8-alpine
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./logs:/var/log/nginx
      - ./static/:/var/www/static
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - frontend
      - backend
      - database
volumes:
  pg_database: