version: "3.8"

services:
  frontend:
    image: goooodmafia/frontend
    container_name: frontend_app
#    ports:
#      - "3000:3000"
    expose:
      - "3000"

  backend:
    image: goooodmafia/backend
    container_name: backend_app
    env_file:
      - ./backend/.env
#    ports:
#      - "8000:8000"
    expose:
      - "8000"
    command: sh -c "./manage.py collectstatic --no-input && gunicorn --bind :8000 --workers 3 app.wsgi"
    volumes:
      - ./static/:/app/static