# Generated by Django 3.2.9 on 2021-11-09 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Отделение')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название ЛПУ')),
                ('address', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='morfis_core.address', verbose_name='Адресс ЛПУ')),
            ],
            options={
                'verbose_name': 'Учереждение',
                'verbose_name_plural': 'Учереждения',
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название филиала')),
                ('master_subdivision', models.BooleanField(default=False, verbose_name='Основное подразделение')),
                ('address', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='morfis_core.address', verbose_name='Адресс филиала')),
                ('departaments', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='morfis_core.department', verbose_name='Отделения')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='morfis_core.hospital', verbose_name='Основное учреждение')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.AddConstraint(
            model_name='subdivision',
            constraint=models.UniqueConstraint(condition=models.Q(('master_subdivision', True)), fields=('master_subdivision',), name='master_subdivision'),
        ),
    ]
