# Generated by Django 3.2.9 on 2021-11-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commoninfo_requests_created', to=settings.AUTH_USER_MODEL)),
                ('lastmodified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commoninfo_requests_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Отделение')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название ЛПУ')),
                ('address', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='morfis_core.address', verbose_name='Адресс ЛПУ')),
            ],
            options={
                'verbose_name': 'Учереждение',
                'verbose_name_plural': 'Учереждения',
            },
        ),
        migrations.CreateModel(
            name='IcdCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='Код диагноза')),
                ('disease_description', models.CharField(max_length=255, verbose_name='Название диагнозa')),
                ('parent_code', models.CharField(max_length=255, verbose_name='Код родителя')),
            ],
            options={
                'verbose_name': 'Код международной классификации болезней',
                'verbose_name_plural': 'Коды международной классификации болезней',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='morfis_core.commoninfo')),
                ('status', models.CharField(choices=[('OPEN', 'Создана'), ('SENDSD', 'Направлена'), ('ACCEPTED', 'Принята'), ('ARCHIVED', 'Архивирована'), ('CLOSE', 'Выполнена')], default='OPEN', max_length=10)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регистрационный номер случая')),
                ('request_timestamp', models.DateTimeField(verbose_name='Дата направления')),
                ('organization', models.CharField(max_length=255, verbose_name='Организация, создавшая направление')),
                ('disease_description', models.TextField(verbose_name='Диагноз заболевания (состояния)')),
                ('order_task', models.TextField(verbose_name='Задача исследования')),
            ],
            options={
                'verbose_name': 'Случай',
                'verbose_name_plural': 'Случаи',
            },
            bases=('morfis_core.commoninfo',),
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название филиала')),
                ('master_subdivision', models.BooleanField(default=False, verbose_name='Основное подразделение')),
                ('address', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='morfis_core.address', verbose_name='Адресс филиала')),
                ('departaments', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='morfis_core.department', verbose_name='Отделения')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='morfis_core.hospital', verbose_name='Основное учреждение')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.AddConstraint(
            model_name='subdivision',
            constraint=models.UniqueConstraint(condition=models.Q(('master_subdivision', True)), fields=('master_subdivision',), name='master_subdivision'),
        ),
        migrations.AddField(
            model_name='case',
            name='mkb_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morfis_core.icdcode', verbose_name='Код МКБ'),
        ),
        migrations.AddField(
            model_name='case',
            name='subdivision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='morfis_core.subdivision', verbose_name='Филиал'),
        ),
    ]
