# Generated by Django 3.2.9 on 2022-01-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='organization',
        ),
        migrations.AlterField(
            model_name='case',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='morfis_core.hospital', verbose_name='Учреждение'),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
