# Generated by Django 3.2.9 on 2021-11-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('commoninfomixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='morfis_core.commoninfomixin')),
                ('status', models.CharField(choices=[('OPEN', 'Создана'), ('SENDSD', 'Направлена'), ('ACCEPTED', 'Принята'), ('ARCHIVED', 'Архивирована'), ('CLOSE', 'Выполнена')], default='OPEN', max_length=10)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Регистрационный номер случая')),
                ('request_timestamp', models.DateTimeField(verbose_name='Дата направления')),
                ('organization', models.CharField(max_length=255, verbose_name='Организация, создавшая направление')),
                ('disease_description', models.TextField(verbose_name='Диагноз заболевания (состояния)')),
                ('order_task', models.TextField(verbose_name='Задача исследования')),
            ],
            options={
                'verbose_name': 'Случай',
                'verbose_name_plural': 'Случаи',
            },
            bases=('morfis_core.commoninfomixin',),
        ),
        migrations.AlterModelOptions(
            name='icdcode',
            options={'ordering': ['pk'], 'verbose_name': 'Код международной классификации болезней', 'verbose_name_plural': 'Коды международной классификации болезней'},
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='case',
            name='mkb_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morfis_core.icdcode', verbose_name='Код МКБ'),
        ),
    ]
