# Generated by Django 3.2.9 on 2021-11-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_core', '0002_commoninfomixin_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
