# Generated by Django 3.2.9 on 2021-11-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_core', '0002_auto_20211119_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'verbose_name': 'Учереждение', 'verbose_name_plural': 'Учереждения'},
        ),
        migrations.RemoveConstraint(
            model_name='subdivision',
            name='master_subdivision',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='departaments',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='master_subdivision',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
