# Generated by Django 3.2.9 on 2021-11-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_core', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id_number',
            field=models.CharField(max_length=255, verbose_name='Регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Создана'), ('SENDSD', 'Направлена'), ('ACCEPTED', 'Принята'), ('ARCHIVED', 'Архивирована'), ('CLOSE', 'Выполнена')], default='OPEN', max_length=10),
        ),
    ]
