# Generated by Django 3.2.9 on 2021-11-26 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_core', '0004_rename_subdivision_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='morfis_core.address', verbose_name='Адресс учереждения'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название учереждения'),
        ),
    ]
