# Generated by Django 3.2.9 on 2022-02-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_core', '0004_remove_organization_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='morfis_core.address', verbose_name='Адрес организации'),
        ),
    ]
