# Generated by Django 3.2.9 on 2021-12-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_core', '0005_auto_20211126_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='subdivision',
            new_name='hospital',
        ),
    ]
