# Generated by Django 3.2.9 on 2021-12-09 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_core', '0005_auto_20211126_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Создана'), ('SENDED', 'Направлена'), ('ACCEPTED', 'Принята'), ('ARCHIVED', 'Архивирована'), ('CLOSE', 'Выполнена')], default='OPEN', max_length=10),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название организации')),
                ('address', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='morfis_core.address', verbose_name='Адрес организации')),
            ],
        ),
    ]
