# Generated by Django 3.2.9 on 2021-12-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_core', '0006_auto_20211208_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
    ]
