# Generated by Django 3.2.9 on 2021-12-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_core', '0006_auto_20211209_0745'),
        ('morfis_core', '0006_rename_subdivision_case_hospital'),
        ('morfis_core', '0007_alter_organization_options'),
    ]

    operations = [
    ]
