# Generated by Django 3.2.9 on 2021-11-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_core', '0002_auto_20211115_1416'),
        ('morfis_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorfisAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morfis_core.subdivision')),
            ],
        ),
    ]
