# Generated by Django 3.2.9 on 2021-12-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_auth', '0003_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morfisuser',
            old_name='subdivision',
            new_name='hospital',
        ),
    ]
