# Generated by Django 3.2.9 on 2021-11-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morfis_auth', '0003_auto_20211116_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MorfisAccount',
        ),
    ]
